server:
  error:
    include-message: always


spring:
#  application:
#    name: project-localstack
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: 12345
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
localstack:
  s3:
    endpoint: http://localhost:4566
  sqs:
    endpoint: http://localhost:4576
bucket:
  name: local-bucket
